server:
  applicationConnectors:
    - type: http
      port: 9215
  adminConnectors:
    - type: http
      port: 9216

logging:
  level: DEBUG
  appenders:
    - type: file
      currentLogFilename: "/var/log/searchmetrics/sm-sm-audit-job-config/application.log"
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: "/var/log/searchmetrics/sm-sm-audit-job-config/application.%i.log.zip"
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{ISO8601} %-5p [%t] %c{1}: %m%n"
      maxFileSize: 10MB

n3service:
  url: "http://docker:8080"
  maxConnections: 200
  connectionTimeout: 20000
  readTimeout: 20000

### KV Store ###
cassandra:
  hosts:
    - "rudolfsteiner.unbelievable-machine.net"
  port: 9042
  keyspace: audit_job_config


swagger:
  resourcePackage: com.searchmetrics.audit.job.config.api.rest
